/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

/**
 *
 * @author mucun
 */
import javax.swing.JOptionPane;
public class VentanaInicio extends javax.swing.JFrame {

    /**
     * Creates new form VentanaInicio
     */
    public VentanaInicio() {
        initComponents();
        setLocationRelativeTo(null); // Centrar ventana
        setTitle("Calculadora de Integrales y Derivadas");
        
        //Acciones de los botones
         btnIntDef.addActionListener(e -> {
            new operaciones.IntegralDefinida().setVisible(true);
            dispose(); // Cierra esta ventana
        });

        btnIntInde.addActionListener(e -> {
            new operaciones.IntegralIndefinida().setVisible(true);
            dispose();
        });

        btnDeriDef.addActionListener(e -> {
            if (chboxEnX.isSelected()){
            new operaciones.DerivadaDefinida().setVisible(true);
              dispose();
            }
              if (chboxEnY.isSelected()){
            new operaciones.DerivadaDefinida().setVisible(true);
              dispose();
              } else{
            JOptionPane.showMessageDialog(this,"Debe seleccionar una variante a trabajar","Error:",JOptionPane.ERROR_MESSAGE);
            }
          
        });

        btnDeriInde.addActionListener(e -> {
            if (chboxEnX.isSelected()){
            new operaciones.DerivadaIndefinida().setVisible(true);
              dispose();
              return;
            }
              if (chboxEnY.isSelected()){
            new operaciones.DerivadainDefinida2().setVisible(true);
              dispose();
              } else{
            JOptionPane.showMessageDialog(this,"Debe seleccionar una variante a trabajar","Error:",JOptionPane.ERROR_MESSAGE);
            }
          
        });

        btnSalir.addActionListener(e -> System.exit(0));
        
        // Checkboxes (solo uno a la vez)
        chboxEnX.addActionListener(e -> {
            if (chboxEnX.isSelected()) chboxEnY.setSelected(false);
            
        });
        chboxEnY.addActionListener(e -> {
            if (chboxEnY.isSelected()) chboxEnX.setSelected(false);
        });
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnIntDef = new javax.swing.JButton();
        btnIntInde = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnDeriDef = new javax.swing.JButton();
        btnDeriInde = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        chboxEnX = new javax.swing.JCheckBox();
        chboxEnY = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Calculadora de Integrales y Derivadas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 654, 43));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Creado con Java POO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 450, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/Umg.png"))); // NOI18N
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setMaximumSize(new java.awt.Dimension(10, 10));
        jLabel3.setMinimumSize(new java.awt.Dimension(10, 10));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 130));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Integrales:");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 90, 20));

        btnIntDef.setText("Definidas");
        getContentPane().add(btnIntDef, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 110, -1));

        btnIntInde.setText("Indefinidas");
        getContentPane().add(btnIntInde, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 110, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Derivadas:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 130, -1));

        btnDeriDef.setText("Definidas");
        getContentPane().add(btnDeriDef, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 110, -1));

        btnDeriInde.setText("Indefinidas");
        getContentPane().add(btnDeriInde, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 110, -1));

        btnSalir.setText("Salir");
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 230, -1));

        chboxEnX.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chboxEnX.setText("En X");
        getContentPane().add(chboxEnX, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, -1));

        chboxEnY.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chboxEnY.setText("En Y");
        getContentPane().add(chboxEnY, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, -1, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Cristhian Cesar Felipe Mucún Queché 2290-17-17851  ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 630, 20));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Maco Levy Mendoza Sacach 2290-24-7123");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 530, -1));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Bryan Emanuel Anleu Rodríguez 2290-20-23001 ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 390, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeriDef;
    private javax.swing.JButton btnDeriInde;
    private javax.swing.JButton btnIntDef;
    private javax.swing.JButton btnIntInde;
    private javax.swing.JButton btnSalir;
    private javax.swing.JCheckBox chboxEnX;
    private javax.swing.JCheckBox chboxEnY;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
