package operaciones;

import javax.swing.JOptionPane;

/**
 *
 * @author
 */
public class IntegralDefinida extends javax.swing.JFrame {

    /**
     * Creates new form IntegralDefinida
     */
    public IntegralDefinida() {
        initComponents();
        setLocationRelativeTo(null); // Centrar ventana
        setTitle("Integral Definida");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        BtnRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Ingreso_LimInferior = new javax.swing.JTextField();
        Ingreso_LimSuperior = new javax.swing.JTextField();
        BtnCalcular = new javax.swing.JButton();
        Ingreso_Entero = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Ingreso_Exponente = new javax.swing.JTextField();
        Btn_Limpiar = new javax.swing.JButton();
        Btn_Graficar_Funcion = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenu2.setText("jMenu2");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnRegresar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnRegresar.setText("Regresar");
        BtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegresarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("Integrales definidas");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/integral.png"))); // NOI18N

        Ingreso_LimInferior.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Ingreso_LimInferior.setText("LI");

        Ingreso_LimSuperior.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Ingreso_LimSuperior.setText("LS");
        Ingreso_LimSuperior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ingreso_LimSuperiorActionPerformed(evt);
            }
        });

        BtnCalcular.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnCalcular.setText("Calcular");
        BtnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCalcularActionPerformed(evt);
            }
        });

        Ingreso_Entero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel3.setText("x");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel4.setText("dx");

        Ingreso_Exponente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ingreso_ExponenteActionPerformed(evt);
            }
        });

        Btn_Limpiar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Btn_Limpiar.setText("Limpiar");
        Btn_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LimpiarActionPerformed(evt);
            }
        });

        Btn_Graficar_Funcion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Btn_Graficar_Funcion.setText("Grafica");
        Btn_Graficar_Funcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Graficar_FuncionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(Ingreso_Exponente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(BtnRegresar)
                                .addGap(18, 18, 18)
                                .addComponent(Btn_Limpiar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addComponent(Btn_Graficar_Funcion))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(151, 151, 151)
                                .addComponent(Ingreso_LimSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Ingreso_LimInferior, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(73, 73, 73))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Ingreso_Entero, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(BtnCalcular))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Ingreso_LimSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Ingreso_LimInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(BtnRegresar)
                                .addComponent(Btn_Limpiar))
                            .addComponent(Btn_Graficar_Funcion))
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(Ingreso_Exponente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(Ingreso_Entero, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnCalcular)
                        .addGap(68, 68, 68))))
        );

        Ingreso_LimSuperior.getAccessibleContext().setAccessibleName("LimSuperior");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegresarActionPerformed
        new ui.VentanaInicio().setVisible(true);
            dispose(); // Cierra esta ventana
    }//GEN-LAST:event_BtnRegresarActionPerformed

    private void Ingreso_LimSuperiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ingreso_LimSuperiorActionPerformed

    }//GEN-LAST:event_Ingreso_LimSuperiorActionPerformed

    private void BtnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCalcularActionPerformed
       try {
        String Limite_SuperiorStr = Ingreso_LimSuperior.getText().trim();
        String Limite_InferiorStr = Ingreso_LimInferior.getText().trim();
        String Entero_Str = Ingreso_Entero.getText().trim();
        String Exponente_Str = Ingreso_Exponente.getText().trim();
        
        
        //verificar que los campos de los limites sean llenados
        if (Limite_SuperiorStr.isEmpty() || Limite_InferiorStr.isEmpty()){
            JOptionPane.showMessageDialog(this, "Debes ingresar todos los valores de la Integral", "Error", JOptionPane.ERROR_MESSAGE);
        }
       
        //Conversion a numeros y validar
        int Limite_Superior;
        int Limite_Inferior;
        int Entero;
        int Exponente;
        
       
        
        try {
            Limite_Superior = Integer.parseInt(Limite_SuperiorStr);
            Limite_Inferior = Integer.parseInt(Limite_InferiorStr);
            Entero = Integer.parseInt(Entero_Str);
            Exponente = Integer.parseInt(Exponente_Str);
            
            
         //
         if (Limite_Superior < Limite_Inferior){
             JOptionPane.showMessageDialog(this, "Error, el limite superior debe ser mayor al limite inferior", "Error", JOptionPane.ERROR_MESSAGE);
         } else {
             if (Limite_Superior == Limite_Inferior){
                 JOptionPane.showMessageDialog(this, "Error, el limite superior debe ser diferente al limite inferior", "Error", JOptionPane.ERROR_MESSAGE);
             }
      
         }
            //Metodo de resultado
          try  { 
            int Divisor = Exponente + 1;
            double Dividendo_Superior = Math.pow(Limite_Superior, Divisor);
            double Dividendo_Inferior = Math.pow(Limite_Inferior, Divisor);
            double Resultado1 = ((Dividendo_Superior * Entero) / Divisor);
            double Resultado2 = ((Dividendo_Inferior * Entero) / Divisor);
            double Resultado_Final = (((Resultado1 - Resultado2)));
            JOptionPane.showMessageDialog(this, "Resultado de la Integral: " + Resultado_Final + "\n∫" + 
                    Entero + "x^" + Exponente + " dx desde " + Limite_Inferior + " hasta " + Limite_Superior);
            } 
          catch (Exception e){
                JOptionPane.showMessageDialog(this, "Error al calcular el resultado final", "Error", JOptionPane.ERROR_MESSAGE);
            }
   
        }
        catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Error, los valores de la integral deben ser numeros validos", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
        }
       catch (Exception e) {
           JOptionPane.showMessageDialog(this, "Error inesperado al calcular: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_BtnCalcularActionPerformed

    private void Ingreso_ExponenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ingreso_ExponenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ingreso_ExponenteActionPerformed

    private void Btn_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LimpiarActionPerformed
        //Boton para quitar los datos puestos
        Ingreso_LimSuperior.setText("");
        Ingreso_LimInferior.setText("");
        Ingreso_Entero.setText("");
        Ingreso_Exponente.setText("");
    }//GEN-LAST:event_Btn_LimpiarActionPerformed

    private void Btn_Graficar_FuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Graficar_FuncionActionPerformed
        //
         try {
        // Obtener la función de tu interfaz (ajusta según tus componentes)
        String funcion = ""; // Aquí obtén la función de tu JTextField
        
        // Si no tienes un campo específico, pedir la función
        if (funcion.isEmpty()) {
            funcion = JOptionPane.showInputDialog(this, 
                "Ingresa la función a graficar:\nEjemplos: x^2, sin(x), 2*x+3", 
                "Graficar Función", JOptionPane.QUESTION_MESSAGE);
            
            if (funcion == null || funcion.trim().isEmpty()) {
                return; // Usuario canceló
            }
        }
        
        funcion = funcion.trim();
        
        // Crear y mostrar el graficador
        GraficadorFunciones graficador = new GraficadorFunciones(funcion);
        graficador.setVisible(true);
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, 
            "Error al crear el gráfico: " + e.getMessage(),
            "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
        //
    }//GEN-LAST:event_Btn_Graficar_FuncionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntegralDefinida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntegralDefinida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntegralDefinida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntegralDefinida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntegralDefinida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCalcular;
    private javax.swing.JButton BtnRegresar;
    private javax.swing.JButton Btn_Graficar_Funcion;
    private javax.swing.JButton Btn_Limpiar;
    private javax.swing.JFormattedTextField Ingreso_Entero;
    private javax.swing.JTextField Ingreso_Exponente;
    private javax.swing.JTextField Ingreso_LimInferior;
    private javax.swing.JTextField Ingreso_LimSuperior;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    // End of variables declaration//GEN-END:variables
}